# Generated by Django 3.0.3 on 2020-07-13 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_to_do_app', '0002_todo_isdont'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='isDont',
            new_name='isDone',
        ),
    ]
